site_name: Моя документация
theme:
  name: material
nav:
  - Главная: index.md
  - Продвинутый пример: advanced-example.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - footnotes